[package]
name = "snake"
version = "0.1.0"
authors = ["max <mx.sht06@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2.1"
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
